name: build
on: [push, pull_request]
jobs:
  main-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core SDK 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - uses: paulhatch/semantic-version@v4.0.2
        id: semantic_version
        with:
          tag_prefix: "v"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build AeccGrouper
        run: dotnet build --configuration Release --no-restore AeccGrouper -o ./bin
      - name: Upload Compiled Binaries
        uses: actions/upload-artifact@v2
        with:
          name: dotnetcore-bin
          path: bin/
      - name: Package AeccGrouper
        run: dotnet pack --configuration Release --no-restore AeccGrouper -o ./nupkgs /p:Version=${{ steps.semantic_version.outputs.VERSION }}
      - name: Upload AeccGrouper Package
        uses: actions/upload-artifact@v2
        with:
          name: AeccGrouper.nupkg
          path: nupkgs/AeccGrouper.*
  test:
    needs: [main-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test AeccGrouper.Tests  --no-restore --logger GitHubActions
  publish:
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Verify commit exists in origin/main
      run: git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Download AeccGrouper.nupkg
      uses: actions/download-artifact@v2
      with:
        name: 'AeccGrouper.nupkg'
        path: ./nupkgs
    - name: Setup .NET Core SDK 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Push to Github Repository
      run: dotnet nuget push ./nupkgs/*.nupkg --source https://nuget.pkg.github.com/pgodwin/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish the package to nuget.org
      run: dotnet nuget push ./nupkgs/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      